name = "software-fauna"
author = "alraro"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d8cec3e395f063c904f15bd6e082a45efdf9c9f847469dccbebd36925fc73d7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
