name = "software-fauna"
author = "alraro"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7ef28f62d0ca37c88983cca53eb4037746af4d54fcf4a61c65ea4dbb764e1b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
