name = "software-fauna"
author = "alraro"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2f8dd1b05ed6f52fd46e0342361ad889f50a8321ff7bf0de8b5a56534fa6968"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
